name: CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Clean install dependencies
        run: npm ci
        
      - name: Run unit tests
        run: npm run test --if-present

  deploy:
    runs-on: ubuntu-latest
    
    needs: [ test ]
    
    steps:  
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        
    - name: Clean install dependencies
      run: npm ci

    ##REPLACE THIS
    - name: Deploy to Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}
        
